# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  # - run: npm test
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    # || true is a quick and dirty way to make sure it passes this step because there's no assets directory in use right now
    - run: cp assets/* dist/assets/ || true
    - run: git --work-tree dist add --all
    - run: git commit -m "Automatic Build & Deploy"
    - run: git push origin HEAD:gh-pages --force
